spring:
    application:
        name: auth-service
    
    config:
        import: file:src\main\resources\env.properties
    
    mvc:
        view:
            suffix: .html

    datasource:
        url: jdbc:postgresql://localhost:5432/auth
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        # database-platform: org.hibernate.dialect.MySQL8Dialect
    
    # mail:
    #     host: smtp.gmail.com
    #     port: 587
    #     username: ${MAIL_USERNAME}
    #     password: ${MAIL_PASSWORD}
    #     properties:
    #         mail:
    #             smtp:
    #                 auth: true
    #                 starttls:
    #                     enable: true
    
    # data:
    #     redis:
    #         host: localhost
    #         port: 6379

server:
    port: 8080

eureka:
  client:
    enabled: false
    register-with-eureka: false
    fetch-registry: false

auth:
    token:
        secret-key: ${JWT_SECRET_KEY}
        jwt-expiration: 10800000        # 3 hours
        refresh-expiration: 604800000   # 7 days
        token-expiration: 3600000       # 1 hour
    admin:
        username: ${ADMIN_USERNAME}
        password: ${ADMIN_PASSWORD}
    cors:
        allowed-origins:
            - "http://localhost:3000"   # <--- FIX: Put your React/Frontend URL here
            - "http://localhost:5173"   # <--- (Optional) Vite default port
        allowed-methods: 
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
        allowed-headers: 
            - "*"  # Allow all headers (easier for development)
